-- LISTER LES COMPETENCES DES HOTE
DROP PROCEDURE IF EXISTS lister_competences_hote;
DELIMITER |
CREATE PROCEDURE lister_competences_hote()
BEGIN
    SELECT UTILISATEUR.nom, UTILISATEUR.prenom, GROUP_CONCAT(ACTIVITE.libelle SEPARATOR ', ') as activites
    FROM UTILISATEUR 
    RIGHT JOIN ACTIVITE_HOTE
    ON UTILISATEUR.id = ACTIVITE_HOTE.idHote
    RIGHT JOIN ACTIVITE ON ACTIVITE.id = ACTIVITE_HOTE.idActivite 
    WHERE UTILISATEUR.idRole = 1
    GROUP BY UTILISATEUR.id;
END|
DELIMITER ;