-- SCRIPT SUPPRESSION DES DONNEES DE LA BASE ET REINSERTION DE DONNEES
DROP PROCEDURE IF EXISTS regenerateDatas;
DELIMITER |
CREATE PROCEDURE regenerateDatas()
BEGIN
    DELETE FROM ACTIVITE_HOTE;
    ALTER TABLE ACTIVITE_HOTE AUTO_INCREMENT =1;

    DELETE FROM ACTIVITE;
    ALTER TABLE ACTIVITE AUTO_INCREMENT =1;

    DELETE FROM WOOFING;
    ALTER TABLE WOOFING AUTO_INCREMENT =1;

    DELETE FROM VALIDER;
    ALTER TABLE VALIDER AUTO_INCREMENT =1;
    
    DELETE FROM TYPEACT_CHANTIER;
    ALTER TABLE TYPEACT_CHANTIER AUTO_INCREMENT =1;

    DELETE FROM NIVEAU;
    ALTER TABLE NIVEAU AUTO_INCREMENT =1;

    DELETE FROM TYPE_ACTIVITE;
    ALTER TABLE TYPE_ACTIVITE AUTO_INCREMENT =1;

    DELETE FROM CHANTIER;
    ALTER TABLE CHANTIER AUTO_INCREMENT =1;

    DELETE FROM HOTE;
    ALTER TABLE HOTE AUTO_INCREMENT =1;

    DELETE FROM UTILISATEUR;
    ALTER TABLE UTILISATEUR AUTO_INCREMENT =1;

    DELETE FROM ROLE;
    ALTER TABLE ROLE AUTO_INCREMENT =1;

    CALL generateDatas();

END|
DELIMITER ;